name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # every midnight UTC
  workflow_dispatch:     # enables manual trigger

jobs:
  generate:
    name: Generate Snake SVG
    runs-on: ubuntu-latest

    steps:
      - name: Generate the snake
        uses: Platane/snk@v3
        with:
          github_user_name: 404SkillNotFound
          outputs: dist/github-contribution-grid-snake.svg

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
